version: '3'
services:
  mouse:
    image: 'node:buster'
    command: [ "/bin/sh", "-c", "node /application/index.js; sleep infinity",  ]
    ports:
      - "3000:3000"
    volumes:
      - './mouse:/application'
      - './node_modules:/application/node_modules'
